name: Android CI - Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew || true

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Decode Android keystore (from secret ANDROID_KEYSTORE)
      if: ${{ secrets.ANDROID_KEYSTORE != '' }}
      run: |
        echo "Decoding keystore..."
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android.keystore

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease --no-daemon -Porg.gradle.jvmargs="-Xmx1536m"
        # If you provide keystore and passwords via CLI properties, uncomment the following and comment the above:
        # ./gradlew assembleRelease \\
        #   -Pandroid.injected.signing.store.file=android.keystore \\
        #   -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \\
        #   -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \\
        #   -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}" --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: **/build/outputs/apk/**/**/*.apk

    - name: (optional) Create GitHub Release and attach APK
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: softprops/action-gh-release@v1
      with:
        files: **/build/outputs/apk/**/**/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Detected project summary:
# settings file: not found
# gradlew present: False
# gradle wrapper present: False
# module names / build.gradle locations: ['']
